In [36]:
import numpy as np
import cv2
import numpy.linalg as la
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [37]:
def proj1(pts):
    matr = np.array([pts[0], pts[1], pts[2]]).T
    l = la.solve(matr, np.array(pts[3]).T)
    return np.array([l[0]*pts[0], l[1]*pts[1], l[2]*pts[2]]).T
    return l

In [38]:
def proj(pts):
    l1 = la.det(np.array([pts[3], pts[1], pts[2]]).T);
    l2 = la.det(np.array([pts[0], pts[3], pts[2]]).T);
    l3 = la.det(np.array([pts[0], pts[1], pts[3]]).T);
    return np.array([l1*pts[0], l2*pts[1], l3*pts[2]]).T

In [39]:
def naivni(src, img):
    return np.matmul(proj(img), la.inv(proj(src)))

In [40]:
image_path = 'sveska.jpg'
img = mpimg.imread(image_path)

In [43]:
w = 600
h = 900
tacke = np.array([[1565, 981, 1], [2769, 545, 1], [4121, 2225, 1], [2813, 3157, 1]])
slike_tacaka = np.array([[0, 0, 1], [w-1, 0, 1], [w-1, h-1, 1], [0, h-1, 1]])

P = naivni(tacke, slike_tacaka)
print(P)
img_new = cv2.warpPerspective(img, P, (w, h))
cv2.imshow('window',img_new)
cv2.imwrite('nova.jpg', img_new)
cv2.waitKey()
cv2.destroyAllWindows()

[[ 5.53296649e-02 -3.17331902e-02 -5.54606661e+01]
 [ 2.55379912e-02  7.05223427e-02 -1.09149374e+02]
 [-7.79771265e-06  2.76342609e-05  1.40842692e-01]]
