In [248]:
import numpy as np
import numpy.linalg as la

In [249]:
def aff2hom(t):
    return np.append(t, 1)

In [250]:
def hom2aff(t):
    if(t[-1] == 0):
        raise ZeroDivisionError("deljenje nulom")
    return t[:-1]/t[-1]

In [251]:
def prosek(a,b,c):
    a1 = hom2aff(a)
    b1 = hom2aff(b)
    c1 = hom2aff(c)
    return (a1+b1+c1)/3

In [252]:
def osmoTeme(t1, t2, t3, t5, t6, t7, t8):
    p15 = np.cross(t1, t5)
    p26 = np.cross(t2, t6)
    p37 = np.cross(t3, t7)

    Xb1 = np.cross(p15, p26)
    Xb2 = np.cross(p15, p37)
    Xb3 = np.cross(p26, p37)
    Xb = aff2hom(prosek(Xb1, Xb2, Xb3))

    p12 = np.cross(t1, t2)
    p56 = np.cross(t5, t6)
    p78 = np.cross(t7, t8)

    Yb1 = np.cross(p12, p56)
    Yb2 = np.cross(p12, p78)
    Yb3 = np.cross(p56, p78)
    Yb = aff2hom(prosek(Yb1, Yb2, Yb3))

    p23 = np.cross(t2, t3)
    p58 = np.cross(t5, t8)
    p67 = np.cross(t6, t7)

    Zb1 = np.cross(p23, p58)
    Zb2 = np.cross(p23, p67)
    Zb3 = np.cross(p58, p67)
    Zb = aff2hom(prosek(Zb1, Zb2, Zb3))

    p48 = np.cross(Xb, t8)
    p34 = np.cross(Yb, t3)
    p14 = np.cross(Zb, t1)

    t41 = np.cross(p48, p34)
    t42 = np.cross(p48, p14)
    t43 = np.cross(p34, p14)
    t4 = prosek(t41, t42, t43)
    return aff2hom(t4)

In [253]:
O3 = np.array([0,0,0,0])
def dveJed(Ah, A1h):
    jed1 = np.concatenate((O3, -A1h[2]*Ah, A1h[1]*Ah)) 
    jed2 = np.concatenate(( A1h[2]*Ah, O3, -A1h[0]*Ah))
    return np.array([jed1, jed2])

def matrica_kamere(pts, pts1):
    A = []
    for i in range(len(pts)):
        dve = dveJed(pts[i], pts1[i])
        A.append(dve[0])
        A.append(dve[1])
    np.array(A)
    U,S, Vh = la.svd(A)   
    matP = Vh[-1].reshape(3,4) 
    return matP/matP[-1,-1] 

In [254]:
def centar(T):
    C1 = np.linalg.det(np.delete(T, 0, 1))
    C2 = np.linalg.det(np.delete(T, 1, 1))
    C3 = np.linalg.det(np.delete(T, 2, 1))
    C4 = np.linalg.det(np.delete(T, 3, 1))
    C = np.array([C1, -C2, C3, -C4])*(-1/C4)
    return C

In [255]:
def matrica_kalibracije(T):
    t0 = np.delete(T, 3, 1)
    inverz = np.linalg.inv(t0)
    Q, R = np.linalg.qr(inverz)
    if(R[0,0] < 0):
        R = np.matmul(np.diag([-1,1,1]), R)
        q = np.matmul(Q ,np.diag([-1,1,1]))
    if(R[1,1] < 0):
        R = np.matmul(np.diag([1,-1,1]), R)
        q = np.matmul(Q ,np.diag([1,-1,1]))
    if(R[2,2] < 0):
        R = np.matmul(np.diag([1,1,-1]), R)
        q = np.matmul(Q ,np.diag([1,1,-1]))
    
    K = np.linalg.inv(R)
    return K/K[-1,-1]

In [256]:
c1l = np.array([969, 591, 1])
c2l = np.array([685, 870, 1])
c3l = np.array([507, 732, 1])
c5l = np.array([994, 493, 1])
c6l = np.array([689, 772, 1])
c7l = np.array([488, 624, 1])
c8l = np.array([815, 394, 1])
c4l = np.array(osmoTeme(c1l, c2l, c3l, c5l, c6l, c7l, c8l))

k1l = np.array([1329, 550, 1])
k2l = np.array([1205, 603, 1])
k3l = np.array([1090, 500, 1])
k5l = np.array([1393, 413, 1])
k6l = np.array([1261, 465, 1])
k7l = np.array([1128, 364, 1])
k8l = np.array([1256, 319, 1])
k4l = np.array(osmoTeme(k1l, k2l, k3l, k5l, k6l, k7l, k8l))

c1r = np.array([924, 658, 1])
c2r = np.array([547, 867, 1])
c3r = np.array([446, 712, 1])
c5r = np.array([938, 565, 1])
c6r = np.array([530, 780, 1])
c7r = np.array([417, 615, 1])
c8r = np.array([805, 447, 1])
c4r = np.array(osmoTeme(c1r, c2r, c3r, c5r, c6r, c7r, c8r))

k1r = np.array([1325, 677, 1])
k2r = np.array([1162, 710, 1])
k3r = np.array([1084, 589 ,1])
k5r = np.array([1384, 544, 1])
k6r = np.array([1204, 580, 1])
k7r = np.array([1112, 457, 1])
k8r = np.array([1277, 427, 1])
k4r = np.array(osmoTeme(k1r, k2r, k3r, k5r, k6r, k7r, k8r))

In [257]:
leve = np.array([c5l, c6l, c7l, c8l, k5l, k6l, k7l, k8l])
desne = np.array([c5r, c6r, c7r, c8r, k5r, k6r, k7r, k8r])

In [258]:
im_dim = 1600
leve = np.array([1, -1, -1])*(np.array([im_dim, 0, 0]) - leve)
desne = np.array([1, -1, -1])*(np.array([im_dim, 0, 0]) - desne)

In [259]:
def jed(a, b):
    return np.array([a[0]*b[0], a[1]*b[0], a[2]*b[0], a[0]*b[1], a[1]*b[1], a[2]*b[1], a[0]*b[2], a[1]*b[2], a[2]*b[2]])

def fundamentalna_matrica(l, r):
    A = []
    for i in range(len(l)):
        jna = jed(l[i], r[i])
        A.append(jna)
    np.array(A)
    U,S, Vh = la.svd(A)   
    matP = Vh[-1].reshape(3,3) 
    return matP/matP[-1,-1] 

In [260]:
fm = fundamentalna_matrica(leve, desne)
print(fm)

[[ 2.25029970e-06 -1.70010583e-05  4.92700203e-03]
 [ 2.04524721e-05  8.07959497e-06  2.35769775e-03]
 [-8.30387870e-03 -1.04849222e-02  1.00000000e+00]]


In [261]:
# kocka = np.array([k1l, k2l, k3l, k6l, k7l, k8l])
# kocka = np.array([1, -1, -1])*(np.array([im_dim, 0, 0]) - kocka)

# kk1l = np.array([0, 3, 0, 1])
# kk2l = np.array([3, 3, 0, 1])
# kk3l = np.array([3, 0, 0, 1])
# kk6l = np.array([3, 3, 3, 1])
# kk7l = np.array([3, 0, 3, 1])
# kk8l = np.array([0, 0, 3, 1])

# kkocka = np.array([kk1l, kk2l, kk3l, kk6l, kk7l, kk8l])
# T2 = matrica_kamere(kkocka, kocka)
# k1 = matrica_kalibracije(T2)

In [262]:
k1 = np.array([
    [1336, -14, 889],
    [0, 1329, 640],
    [0, 0, 1]
])

In [263]:
ee = k1.T @ fm @ k1
ee

array([[  4.01655094, -30.22821662,  -5.2814202 ],
       [ 36.27217452,  14.20673595,  34.22511203],
       [  9.06638976, -27.24371568,  -0.15188937]])

In [264]:
q0 = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

e0 = np.array([
    [0, 1, 0],
    [-1, 0, 0],
    [0, 0, 0]
])


In [265]:
u, ss, v = la.svd(ee)

In [266]:
ec = u @ e0 @ u.T
aa = u @ q0 @ v
print(ec)
print("----------------")
print(aa)

[[ 2.73962733e-18  7.14565977e-01  1.02699545e-01]
 [-7.14565977e-01  1.66242571e-17 -6.91988633e-01]
 [-1.02699545e-01  6.91988633e-01 -2.88142100e-18]]
----------------
[[-0.10855589  0.07211974 -0.99147081]
 [ 0.35368788 -0.92930101 -0.10632269]
 [-0.92904279 -0.36221316  0.07537323]]


In [267]:
cc = np.array([ec[2][1], ec[0][2], ec[1][0]])
cc

array([ 0.69198863,  0.10269954, -0.71456598])

In [268]:
cc1 = (-aa.T) @ cc
T1 = k1 @ aa.T
T1 = T1.T
T1 = np.append(T1, k1 @ cc1)
T1 = T1.reshape(4, 3)
T1 = T1.T
T1

array([[-1.02745790e+03,  3.91016349e+02, -1.16912338e+03,
        -1.64583806e+02],
       [-5.38694188e+02, -1.30308757e+03, -4.33142432e+02,
         1.97087909e+02],
       [-9.91470807e-01, -1.06322694e-01,  7.53732259e-02,
         7.50864963e-01]])

In [272]:
T2 = np.array([
    [1336, -14, 889, 0],
    [0, 1329, 640, 0],
    [0, 0, 1, 0]
])
print(T2)

[[1336  -14  889    0]
 [   0 1329  640    0]
 [   0    0    1    0]]


In [273]:
def jednacine(t1, t2, m1, m2):
    j = np.array([
        m1[1]*t1[2] - m1[2]*t1[1],
        -m1[0]*t1[2] + m1[2]*t1[0],
        m2[1]*t2[2] - m2[2]*t2[1],
        -m2[0]*t2[2] + m2[2]*t2[0]
    ])
    return j
def triangulacija(t1, t2, m1, m2):
    jedM = jednacine(t1, t2, m1, m2)
    V = la.svd(jedM)[2]
    return hom2aff(V.T[3])

In [274]:
triangulacija(T1, T2, c1l, c1r)

array([-0.10831203, -0.68437248, -0.01115163])